server.port=8080

spring.application.name=api-gateway

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

eureka.instance.instance-id=${spring.application.name}:${server.port}

# User Service
spring.cloud.gateway.server.webflux.routes[0].id=user-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://USER
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/users/**


# Order Service
spring.cloud.gateway.server.webflux.routes[1].id=order-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://ORDER-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/orders/**


# Payment Service
spring.cloud.gateway.server.webflux.routes[2].id=payment-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://PAYMENT
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/payments/**